### ISSUE TITLE
Welcome menu bug

### ISSUE THREAD

**Issue by esibruti** [Rise-Software/Rise-Photos#5]
When opening Rise Photos for the first time, the first screen, in full screen, presents differences if it is the screen in windowed mode.

Window Mode: 
![0](https://user-images.githubusercontent.com/78214358/210168435-8d2fe4a2-1680-4d5a-9014-c9936d6adc3b.jpg)

Full-Screen Mode:
![1](https://user-images.githubusercontent.com/78214358/210168452-92ef2bae-f11e-401c-a5bb-8ebd9a8e8660.jpg)

**Comment by josephbeattie** [comment]
Not a bug. this is intended behaviour.
